# Generated by Django 5.1 on 2024-08-31 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('final_app', '0004_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
